### ISSUE TITLE
Error step 1

### ISSUE THREAD

**Issue by marius1968** [eclair4151/SamsungEncryptServer#1]
I managed to install the script and step 1 works even though it returns the error "System.BadImageFormatException: Could not load file or assembly 'SPCApi, Version=1.0.5304.23677, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.\r\nFile name: 'SPCApi, Version=1.0.5304.23677, Culture=neutral, PublicKeyToken=null"

Can you tell us what you are using for the call to steps 2 and 3? I found the SPCApi.dll commands GenerateServerAck() and GetKey() but I'm not sure at which step they are used.

Thanks.

**Comment by eclair4151** [comment]
From the other thread:


Generate a TVID (you will need it later). (UUID format)
Step 1: GET - http://<TVIP>:8080/ws/apps/CloudPINPage
-> Test if the PIN Page is already displaying on TV. Close if needed (as we re-open it later)

Step 2: POST - http://<TVIP>:8001/ms/1.0/
POST: {"method":"ms.device.getInfo", "id":"<TVID>", "jsonrpc":"2.0", "params":{}}
-> You will get some infos, like capabilities, model (...): You will need it, as some models don't have the 'smart' capabilities (and, btw, no remote)

Step 3: POST - http://<TVIP>:8080/ws/apps/CloudPINPage
POST: pin4
-> You will get the PIN on the TV screen.

Step 4: GET - http://<TVIP>:8080/ws/pairing?step=0&app_id=<some_app_id>&device_id=<TVID>&type=1
-> Init the crypto, will reply with empty {"auth_data":""}

Step 5 (DLL): Call GenerateServerHello(pincode) -> Get CODE1

Step 6: POST - http://<TVIP>:8080/ws/pairing?step=1&app_id=<some_app_id>&device_id=<TVID>
POST: "auth_Data":{"auth_type":"SPC","GeneratorServerHello":"CODE1"}

Step 7 (DLL): Extract, from the reply of STEP 6, requestId and GeneratorClientHello.
Call ParseClientHello(pincode, GeneratorClientHello)
Call GenerateServerAck()
You will now have requestId and the result of GenerateServerAck()

Step 8: POST - http://<ip>:8080/ws/pairing?step=2&app_id=<some_app_id>&device_id=<TVID>
POST: "auth_Data":{"auth_type":"SPC","request_id":"<requestId>","ServerAckMsg":"<GenerateServerAck>"}"
-> You will get session_id, it's for the Websocket session !

Step 9 (DLL): Concatenate "<requestId>,<serverAckMsg>" in a String (note the comma)
Call ParseClientAck(concatenatedString)
call GetKey() -> Hey ! This is the key for the websocket encryption !

**Comment by eclair4151** [comment]
Also what OS are you running it on?

**Comment by marius1968** [comment]
@eclair4151 
Thank you very much for your explanations.
We have failed to use Mono on Linux and installed the application on a Windows server ; this may be the reason for the error.
We want to develop this application for a home automation and we need this development, whether it's Mono on Linux or a Windows server as long as it can expose a service that can be accessed by an external application as you did.
So, if we fail to understand the logic of the script and make the implementation you are willing to help us?
Can we discuss these details privately?

**Comment by eclair4151** [comment]
sure. Also i wrote and tested this on windows so it should work fine there. make sure that the drivers folder is properly linked in the references in visual studio

**Comment by ouija** [comment]
Ugh.  Pardon me for my ignorance, but I've never launched an asp.net application in my life (but do have a lot of familiarity with LAMP based configurations and such, and a little IIS knowledge) and I was hoping to maybe deploy this onto a server (for a mirror or safety) but have no clue how to go about doing so...

Any help or insight you can provide would be greatly appreciated.  Thanks!
