### ISSUE TITLE
Instructions on how to deploy this?

### ISSUE THREAD

**Issue by ouija** [eclair4151/SamsungEncryptServer#2]
Ugh.  Pardon my ignorance, but I have never used asp.net in my life nor do I have any knowledge how to go about deploying this onto a server.  _(I am however very familiar with Linux based server environments and have some experience with AWS and IIS)_

I was hoping to do so as a mirror or safety in case the other ever went offline, and any instructions or insight you can provide in order to get this up and running would be **greatly** appreciated.  

Thank you!

**Comment by eclair4151** [comment]
What have you tried? You should just be able to open it in visual studio and hit run.

**Comment by ouija** [comment]
Oh.  I haven't tried that.. Never ran Visual Studio in my life! haha.  But how does one get this up on a server of some kind where requests can be made?  I'll play around with VS tonight to get some experience with it

**Comment by eclair4151** [comment]
you should just be able to open it in VS on the server, click run and make requests to that computer. It runs by default on port 57885. 

So if you are on the same network just make a post request to

<serverip>:57885/api/Step1

with the json
{
    "pin": "1234",
    "deviceId" : "12345"
}


when you are ready to put it in production just [run it on port 80](https://stackoverflow.com/questions/894103/how-to-make-asp-net-development-server-run-on-port-80)

there are plenty of tutorials on making asp.net production ready so i would just google around

**Comment by ouija** [comment]
Perfect.  Shows my limited knowledge with both VS and ASP.NET -- I had no idea it could run directly in it off the server... ahh shit.... :)

Thanks man!
